AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket and CloudFront distribution with OAC

Parameters:
  DomainName:
    Type: String
    Default: fbd.cmpapp.top
    Description: CNAME for the CloudFront distribution
  AcmCertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:255327957584:certificate/51f2f21b-15e2-4dac-8c75-79c6ef5634fb
    Description: ARN of the existing ACM certificate for *.cmpapp.top

Resources:
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${DomainName}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendCloudFrontDistribution}

  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt FrontendS3Bucket.RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        DefaultRootObject: index.html
        PriceClass: PriceClass_100

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${DomainName}-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: !Ref FrontendS3Bucket
  CloudFrontDistributionId:
    Description: ID of the CloudFront distribution
    Value: !Ref FrontendCloudFrontDistribution
  CloudFrontDomainName:
    Description: Domain name of the CloudFront distribution
    Value: !GetAtt FrontendCloudFrontDistribution.DomainName